## funtion

In [1]:
import pandas as pd
import datetime as dt
import configparser
import logging
import os
def append_byexcel(asserts_excelpath,want_asserts_excelpath,datahistory):
    now=dt.datetime.now()
    formatted_now=now.strftime("%Y_%m_%d_%H%M%S")
    init_asserts=pd.read_excel(r'{}'.format(asserts_excelpath))
    want_asserts=pd.read_excel(r'{}'.format(want_asserts_excelpath))
    append_asserts=pd.concat([init_asserts,want_asserts]).reset_index(drop=True)
    append_asserts.to_excel(r'{}'.format(asserts_excelpath),index=False)
    append_asserts.to_excel(r'{}\asserts_{}.xlsx'.format(datahistory,formatted_now),index=False)
    return append_asserts
def delete_bymonth(Y,M,asserts_excelpath,datahistory):
    now=dt.datetime.now()
    formatted_now=now.strftime("%Y_%m_%d_%H%M%S")
    init_asserts=pd.read_excel(r'{}'.format(asserts_excelpath))
    mask=init_asserts['time']!=dt.datetime(Y, M, 1)
    keep_asserts=init_asserts[mask]
    keep_asserts.to_excel(r'{}'.format(asserts_excelpath),index=False)
    keep_asserts.to_excel(r'{}\asserts_{}.xlsx'.format(datahistory,formatted_now),index=False)
    return keep_asserts
def main():
    thislvPATH=os.getcwd()
    conf = configparser.ConfigParser()
    conf.read(r'{}\config.ini'.format(thislvPATH))
    asserts_excelpath  = conf.get("filepath","asserts")
    want_asserts_excelpath  = conf.get("filepath","want_asserts")

## 配置

In [2]:
thislvPATH=os.getcwd()
conf = configparser.ConfigParser()
conf.read(r'{}\config.ini'.format(thislvPATH))
asserts_excelpath  = conf.get("filepath","asserts")
want_asserts_excelpath  = conf.get("filepath","want_asserts")
datahistory  = conf.get("filepath","datahistory")

## excel新增資料

In [3]:
append_byexcel(asserts_excelpath,want_asserts_excelpath,datahistory).head()

        time type      accont     QTY  TWD_exchange  THB_exchange     TWD  THB
0 2018-10-01  舊資料  舊資料總資產(NT)  118248           1.0           NaN  118248  NaN
1 2018-11-01  舊資料  舊資料總資產(NT)   54449           1.0           NaN   54449  NaN
2 2018-12-01  舊資料  舊資料總資產(NT)   99218           1.0           NaN   99218  NaN
3 2019-01-01  舊資料  舊資料總資產(NT)  138560           1.0           NaN  138560  NaN
4 2019-02-01  舊資料  舊資料總資產(NT)  148193           1.0           NaN  148193  NaN

## 刪除資料BY月份

In [4]:
now=dt.datetime.now()
today=dt.datetime.now()
Y=int(now.strftime('%Y'))
M=int(now.strftime('%m'))
Ystr=input('欲刪除年:')
Mstr=input('欲刪除月:')
Y=int(Ystr)
M=int(Mstr)
delete_bymonth(Y,M,asserts_excelpath,datahistory)

欲刪除年:2021
欲刪除月:6

,time,type,accont,QTY,TWD_exchange,THB_exchange,TWD,THB
0,2018-10-01,舊資料,舊資料總資產(NT),118248,1.00,NaN,118248,NaN
1,2018-11-01,舊資料,舊資料總資產(NT),54449,1.00,NaN,54449,NaN
2,2018-12-01,舊資料,舊資料總資產(NT),99218,1.00,NaN,99218,NaN
3,2019-01-01,舊資料,舊資料總資產(NT),138560,1.00,NaN,138560,NaN
4,2019-02-01,舊資料,舊資料總資產(NT),148193,1.00,NaN,148193,NaN
5,2019-03-01,舊資料,舊資料總資產(NT),183154,1.00,NaN,183154,NaN
6,2019-04-01,舊資料,舊資料總資產(NT),209391,1.00,NaN,209391,NaN
7,2019-05-01,舊資料,舊資料總資產(NT),264032,1.00,NaN,264032,NaN
8,2019-06-01,舊資料,舊資料總資產(NT),299237,1.00,NaN,299237,NaN
9,2019-07-01,舊資料,舊資料總資產(NT),330990,1.00,NaN,330990,NaN
10,2019-08-01,舊資料,舊資料總資產(NT),366331,1.00,NaN,366331,NaN
11,2019-09-01,舊資料,舊資料總資產(NT),416213,1.00,NaN,416213,NaN
12,2019-10-01,舊資料,舊資料總資產(NT),436901,1.00,NaN,436901,NaN
13,2019-11-01,舊資料,舊資料總資產(NT),411319,1.00,NaN,411319,NaN
14,2019-12-01,舊資料,舊資料總資產(NT),445828,1.00,NaN,445828,NaN
15,2020-01-01,舊資料,舊資料總資產(NT),522326,1.00,NaN,522326,NaN
16,2020-02-01,舊資料,舊資料總資產(NT),547498,1.00,NaN,547498,NaN
17,2020-03-01,舊資料,舊資料總資產(NT),578895,1.00,NaN,578895,NaN
18,2020-04-01,舊資料,舊資料總資產(NT),609354,1.00,NaN,609354,NaN
19,2020-05-01,舊資料,舊資料總資產(NT),606594,1.00,NaN,606594,NaN
20,2020-06-01,舊資料,舊資料總資產(NT),663933,1.00,NaN,663933,NaN
21,2020-07-01,舊資料,舊資料總資產(NT),657331,1.00,NaN,657331,NaN
22,2020-08-01,活存,台幣現金(NT),2200,1.00,NaN,2200,NaN
23,2020-08-01,活存,中華郵政(NT),4801,1.00,NaN,4801,NaN
24,2020-08-01,活存,中國信託活存(NT),366733,1.00,NaN,366733,NaN
25,2020-08-01,定存,中國信託定存(NT),202071,1.00,NaN,202071,NaN
26,2020-08-01,活存,richart(NT),30001,1.00,NaN,30001,NaN
27,2020-08-01,活存,Line pay money,29127,1.00,NaN,29127,NaN
28,2020-08-01,活存,泰銖現金(NT),2600,0.95,NaN,2470,NaN
29,2020-08-01,證券戶,新光證券(NT),0,1.00,NaN,0,NaN
...,...,...,...,...,...,...,...,...
73,2021-02-01,活存,中國信託活存(NT),351533,1.00,NaN,351533,NaN
74,2021-02-01,定存,中國信託定存(NT),402071,1.00,NaN,402071,NaN
75,2021-02-01,活存,richart(NT),122089,1.00,NaN,122089,NaN
76,2021-02-01,活存,Line pay money,1300,1.00,NaN,1300,NaN
77,2021-02-01,活存,泰銖現金(NT),2600,0.95,NaN,2470,NaN
78,2021-02-01,證券戶,新光證券(NT),36491,1.00,NaN,36491,NaN
79,2021-03-01,活存,台幣現金(NT),3500,1.00,NaN,3500,NaN
80,2021-03-01,活存,中華郵政(NT),1804,1.00,NaN,1804,NaN
81,2021-03-01,活存,中國信託活存(NT),392251,1.00,NaN,392251,NaN
82,2021-03-01,定存,中國信託定存(NT),402071,1.00,NaN,402071,NaN
83,2021-03-01,活存,richart(NT),104936,1.00,NaN,104936,NaN
84,2021-03-01,活存,Line pay money,4623,1.00,NaN,4623,NaN
85,2021-03-01,活存,泰銖現金(NT),2600,0.95,NaN,2470,NaN
86,2021-03-01,證券戶,新光證券(NT),36491,1.00,NaN,36491,NaN
87,2021-04-01,活存,台幣現金(NT),1200,1.00,NaN,1200,NaN
88,2021-04-01,活存,中華郵政(NT),1804,1.00,NaN,1804,NaN
89,2021-04-01,活存,中國信託活存(NT),439356,1.00,NaN,439356,NaN
90,2021-04-01,定存,中國信託定存(NT),402071,1.00,NaN,402071,NaN
91,2021-04-01,活存,richart(NT),89054,1.00,NaN,89054,NaN
92,2021-04-01,活存,Line pay money,2000,1.00,NaN,2000,NaN
93,2021-04-01,活存,泰銖現金(NT),2600,0.95,NaN,2470,NaN
94,2021-04-01,證券戶,新光證券(NT),36491,1.00,NaN,36491,NaN
95,2021-05-01,活存,台幣現金(NT),1200,1.00,NaN,1200,NaN
96,2021-05-01,活存,中華郵政(NT),1804,1.00,NaN,1804,NaN
97,2021-05-01,活存,中國信託活存(NT),445385,1.00,NaN,445385,NaN
98,2021-05-01,定存,中國信託定存(NT),402071,1.00,NaN,402071,NaN
99,2021-05-01,活存,richart(NT),82334,1.00,NaN,82334,NaN
100,2021-05-01,活存,Line pay money,3000,1.00,NaN,3000,NaN
101,2021-05-01,活存,泰銖現金(NT),2600,0.95,NaN,2470,NaN
102,2021-05-01,證券戶,新光證券(NT),36491,1.00,NaN,36491,NaN